# Generated by Django 5.2.4 on 2025-07-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address_zip_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['first_name', 'last_name'], name='store_custo_first_n_8f83e0_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['-birth_date'], name='store_custo_birth_d_dfb3cc_idx'),
        ),
    ]
